### ISSUE TITLE
[sidebar] Remaining sidebar work for initial implementation

### ISSUE THREAD

**Issue by epixa** [epixa/tbyn#2]
The sidebar is mostly complete, but there are a few remaining tasks before it's ready:

- [x] Total amount from all accounts listed next to "All Accounts" link
- [x] Styling of negative dollar amounts
- [x] Number formatting for dollar amounts
- [x] Add account form in a modal
- [x] Style add account form
- [x] Automatically select recommended budget type in add account form
- [x] Account list item styles when collapsed
- [x] Account list item overflow with ellipses
- [x] Expand/collapse account navs
